### ISSUE TITLE
无法找到命令

### ISSUE THREAD

**Issue by HsiangNianian** [MoeMegu/ThrowIt-Mirai#4]
/perm permit m* pers.moe.throwit-mirai:command.丢
指令不存在: pers.moe.throwit-mirai:command.丢
我把jar放在了diceQQ/plugin里，试了就报错这个
又把jar放在了plugins文件夹里，仍然是这个报错

泛用型 Dice! by 溯洄 & Shiki Ver 2.6.3beta4(603) [GNUC 8.4.0 Feb  6 2022 05:55:07 on
Dice!驱动器 by 安研色Shiki & 溯洄w4123 ver0.2.1(3)[2021-08-08 06:46:17] for CoolQ

Linux服务器

**Comment by MoeMegu** [comment]
此问题为Mirai未正常加载插件所致，请贴出完整日志文件

**Comment by MoeMegu** [comment]
经测试，使用MiraiDice除依赖Mirai版本过低导致的无法检查图片上传状态外，并未出现其他错误信息，故关闭此issue
